module.exports = {
  BASE_URL: 'https://animeflv.net',
  BROWSE_URL: 'https://animeflv.net/browse?',
  SEARCH_URL: 'https://animeflv.net/browse?q=',
  ANIME_VIDEO_URL: 'https://animeflv.net/ver/',
  BASE_EPISODE_IMG_URL: 'https://cdn.animeflv.net/screenshots/',
  BASE_JIKA_URL: ' https://api.jikan.moe/v3/search/anime?q=',
  BASE_MYANIME_LIST_URL : 'https://myanimelist.net/character/',
  BASE_NEWS : 'https://somoskudasai.com/',
  MAL_ID : 'https://myanimelist.net/search/prefix.json?type=anime&keyword=',
  TMO__URL : 'https://lectortmo.com/library?_page=1&page=',
  CUEVANA_URL : 'https://cuevana3.io/',
  CUEVANA_URL_2: 'https://www1.cuevana3.video/',
  CUEVANA_SEARCH_2: 'https://www1.cuevana3.video/search.html?keyword=',
  CUEVANA_SEARCH : 'https://cuevana3.io/?s=',
  TMDB: 'https://www.themoviedb.org',
  TMDB_SEARCH : 'https://www.themoviedb.org/search?language=es&query=',
  TMDB_IMG: 'https://image.tmdb.org/t/p/original/',
  PELISPEDIA: 'https://www.pelispedia.de/',
  PELISPEDIA_SEARCH: 'https://www.pelispedia.de/?s=',
  MEGADEDE: 'https://www.megadede.se/',
  MEGADEDE_SEARCH: 'https://www.megadede.se/?s=',
  FANPELIS: 'https://fanpelis.org/',
  FANPELIS_SEARCH: 'https://fanpelis.org/?s=',
};